Add a basic Travis CI configuration file
Based on the configuration for the nexB/license-expression project. For
now only Linux is supported as OS X causes

error: can't combine user with prefix, exec_prefix/home, or install_(plat)base

see https://travis-ci.org/sschuberth/spdx-tools-python/jobs/200046170.